### PR TITLE
Des 634

### PR DESCRIPTION
**Pull request by wyseguyonline**
This is just for the loading spinner.  The full loading indicator will be a component-archetype based component.

### CODE REVIEW

**Comment by JasonLantz** [comment]
import React              from 'react';
import expect             from 'expect';
import { shallow }        from 'enzyme';
import { LoadingSpinner } from '../index';

describe('LoadingSpinner', () => {

  describe('Basic LoadingSpinner Test', function() {
    beforeEach(function() {
      this.wrapper = shallow(<LoadingSpinner />);
    });

    it('should render the LoadingSpinner as div element', function() {
      expect(this.wrapper.node.type).toEqual('div');
    });

  })
});

**Comment by JasonLantz** [comment]
and add the test to the test path (package.json) b/c it's a level deeper than the scan
,"**/src/**/*.{js,jsx}"


from:
    "collectCoverageFrom": [
      "**/src/*.{js,jsx}"
    ],


to:

    "collectCoverageFrom": [
      "**/src/*.{js,jsx}","**/src/**/*.{js,jsx}"
    ],

**Comment by StommePoes** [comment]
looks good.

**Comment by udhadpa** [comment]
Tests written and approved. Good to merge

**Pull request merged**
