### PR TITLE
Calendar cleanup

### PR DESCRIPTION
**Pull request by mhomolak**
While I was changing the event listener yesterday I saw a few opportunities to simplify some things I had done in Calendar.

- Removed unnecessary class based child components in favor of functional components.
- Further destructured props in two of the three child components.
- Changed `dateFormat` in Datepicker to have a defaultProp of the US format to eliminate a variable and from having to include that prop from the consumers end on every instance of the component.

### CODE REVIEW

**Comment by StommePoes** [comment]
Other than whatever causes these:
Failed tests: 
  calendarTestBeforeClass(elementsSDKTests.functionalTests.CalendarTest)
  datePickerBeforeClass(elementsSDKTests.functionalTests.DatePickerTest)

, seems good.

**Comment by mhomolak** [comment]
Eajaz knows the cause and is working on a fix.

**Comment by umahaea** [comment]
CI passes now: https://travis-ci.org/Pearson-Higher-Ed/compounds/builds/289732522

**Comment by umahaea** [comment]
I know what is the problem with those failed tests. I will put a permanent fix for it sometime sooner.

**Comment by StommePoes** [comment]
cools

**Pull request merged**
