### PR TITLE
Des 471

### PR DESCRIPTION
**Pull request by mhomolak**
Footer component

Test coverage is 73~% but wanted to open up a PR in the meantime.

### CODE REVIEW

**Comment by wyseguyonline** [comment]
Is this ready for review or just a placeholder?

**Comment by mhomolak** [comment]
Ready for review.

**Comment by StommePoes** [comment]
Was this a mocker that didn't work with your tests?

**Comment by umahaea** [comment]
Regression passed: https://travis-ci.org/Pearson-Higher-Ed/ux-test-platform/builds/238054207

Good to merge.

**Pull request merged**
